### ISSUE TITLE
Configuration example

### ISSUE THREAD

**Issue by clintonskitson** [emccode/polly#35]
/etc/polly/config.yml

```
polly:
  store:
    type: boltdb
    endpoints: /tmp/boltdb
    bucket: MyBoltDb_test
  libstorage:
    host: tcp://localhost:7979
    profiles:
      enabled: true
      groups:
      - local=127.0.0.1
    server:
      endpoints:
        localhost:
          address: tcp://localhost:7979
      services:
        mock:
          libstorage:
            driver: mock
        mock2:
          libstorage:
            driver: mock
        vfs:
          libstorage:
            driver: vfs
```
